config/routes.rb
Rails.application.routes.draw do
	root 'pages#index'
  get '/index',    	to: 'pages#index'
  get '/about',   	to: 'pages#about'
  get '/contact', 	to: 'pages#contact'
  get '/portfolio',	to: 'pages#portfolio'
  get '/writing',	to: 'pages#writing'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index 
		render
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def writing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def full_title(page_title = '')
    base_title = "Naomi Sanchez Modeling"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Naomi Sanchez Modelling&copy; by <a href="http://www.thefadco.co.uk">The Fanatical About Design Co</a> powered by 
		<%= link_to image_tag("rails.png", id: "rails", alt: "rails logo"), 'http://rubyonrails.org/' %>
	</small>
	<nav>
		<ul>
            <li><%= link_to image_tag("instagram.png", id: "insta", alt: "Naomi Sanchez Modelling instagram page"), 'https://www.instagram.com/naomisanchezmodeling/' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="container">
        <%= link_to "Naomi Sanchez Modeling", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Portfolio", portfolio_path %></li>
            <li><%= link_to "Writing", writing_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
	<h1 class="center">About</h1>
	<h2>This is the About Page for Naomi Sanchez Modelling
	</h2>
	<p class="center">Coming soon!</p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron">
	<h1 class="center">Contact</h1>
	<h2>This is the Contact Page for Naomi Sanchez Modelling
	</h2>
	<p class="center">Coming soon!</p>
</div>

app/views/pages/index.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
	<h1 class="center">Naomi Sanchez Modeling</h1>
	<h2>This is the homepage for Naomi Sanchez Modeling 
	</h2>
	<div>
	<%= link_to image_tag("background.jpg", class: "center", id: "place", alt: "rainbowface"), 'https://www.instagram.com/naomisanchezmodeling/'  %></div>
	<p class="center">Coming soon!</p>
</div>

app/views/pages/portfolio.html.erb
<% provide(:title, "Portfolio") %>
<div class="center jumbotron">
	<h1 class="center">Portfolio</h1>
	<h2>This is the Portfolio Page for Naomi Sanchez Modelling
	</h2>
	<p class="center">Coming soon!</p>
</div>

app/views/pages/writing.html.erb
<% provide(:title, "Writing") %>
<div class="center jumbotron">
	<h1 class="center">Writing</h1>
	<h2>This is the Writing Page for Naomi Sanchez Modelling
	</h2>
	<p class="center">Coming soon!</p>
</div>